run:
  timeout: 5m
  issues-exit-code: 1

linters:
  enable:
  - errname
  - errorlint
  - errcheck
  - errorlint
  - unused
  - godot
  - goerr113
  - gofmt
  - gofumpt
  - gosec
  - misspell
  - revive
  - thelper
  - unconvert
  - unconvert
  - whitespace
  - staticcheck
  disable:
  - structcheck

linters-settings:
  errcheck:
    exclude-functions:
      # tfproviderlint covers the errcheck.
      - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set
