name: code
on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - '**/*.go'
      - '.github/workflows/*.yml'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 0
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # actions/setup-go@v3
        name: Setup Go
        with:
          go-version: 1.19
          cache: true
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
