name: code
on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - '**/*.go'
      - '**/*.mod'
      - '**/*.sum'
      - '.github/workflows/*.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - name: Build
        run: make build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - name: Test
        run: make test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true
      # TODO(amalucelli): Add the tflint once this issue is solved:
      # https://github.com/bflad/tfproviderlint/issues/255
